### ISSUE TITLE
一些issues（好像没有bug了）

### ISSUE THREAD

**Issue by GDWGH** [PatchyVideo/patchyvideo-vue#192]
使用中文 
我遇到的第一个bug是上传视频完之后可能会出现 上传成功弹窗 永远保留在那里
像这样
![1](https://user-images.githubusercontent.com/57795156/103471562-cc32be00-4dbc-11eb-9411-75022e5be821.png)
第二个是浏览器不适应
（1）
网站经常需要缩放 每次打开网站的时候都要缩放（手机上的yandex浏览器和我的microsoft edge 版本 76.0.160.0（正式版本） （64 位）都出现过）
 90%
![90%](https://user-images.githubusercontent.com/57795156/103471631-77437780-4dbd-11eb-8ab6-86e6aa88f278.png)
 100%
![image](https://user-images.githubusercontent.com/57795156/103471635-7e6a8580-4dbd-11eb-8f8b-ebf99c939945.png)
(2)希望能有site app chromium扩展的site app不是很好

**Comment by GDWGH** [comment]
> 2021/2/6 20点49分再补充
> 在搜索输入框中输入
> 例子：帕秋莉 之后输入框给我补全tag 帕秋莉·诺蕾姬 点击第一次搜索按钮 它不起作用 当我点击第二次搜索按钮是 它这才跳转页面

2021/2/10 再次复现一下第三个 bug GitHub我这里网络传不了（烂广东移动）
https://ws28.cn/f/4oj2rl9ro8e
制作组要加油啊

**Comment by wrzrmzx** [comment]
这里看到问题了。。。不过当时因为使用了elementUI的自动补全框所以现在改起来可能有些费劲orz
现在的想法是在新版页面里自己造轮子来彻底解决这个问题。。。
不过感谢建议QAQ

**Comment by GDWGH** [comment]
2021/2/20再次上传bug

**Comment by GDWGH** [comment]
上传视频的时候（特别是第二个视频） 会保留前一个的标签  希望上传页出一个清除所有标签 或者 打勾的标签去除 的按钮

https://user-images.githubusercontent.com/57795156/108597514-6cbc5c00-73c4-11eb-8f20-ac364bd661d8.mp4

**Comment by wrzrmzx** [comment]
这个问题的确值得考虑，这里会尽快进行完善的（不过因为正在搞新页面所以现在页面的更新速度没有那么快orz），感谢！

**Comment by GDWGH** [comment]
> 这个问题的确值得考虑，这里会尽快进行完善的（不过因为正在搞新页面所以现在页面的更新速度没有那么快orz），感谢！
其实还有bug（抓视频的机器人的） 之前在站看到一个无关的视频 然后就点进原视频看来下 好像机器人是抓取 下面的详细的
原视频这样写的：XXX（XXX是其他游戏）XXX XXX 东方project XXX XXX XXX
在他的个人空间里也是这样 不过那个视频的tag没有东方
还有能不能添加一个 西瓜视频 的发布通道（别让机器人在西瓜视频通道里 做上面的事 只指开通个人上传 不开通机器人上传）

**Comment by wrzrmzx** [comment]
> > 这个问题的确值得考虑，这里会尽快进行完善的（不过因为正在搞新页面所以现在页面的更新速度没有那么快orz），感谢！
> > 其实还有bug（抓视频的机器人的） 之前在站看到一个无关的视频 然后就点进原视频看来下 好像机器人是抓取 下面的详细的
> > 原视频这样写的：XXX（XXX是其他游戏）XXX XXX 东方project XXX XXX XXX
> > 在他的个人空间里也是这样 不过那个视频的tag没有东方
> > 还有能不能添加一个 西瓜视频 的发布通道（别让机器人在西瓜视频通道里 做上面的事 只指开通个人上传 不开通机器人上传）

啊这个问题应该是机器人识别的准确率还有待提升，后续会继续进行优化的。。。不过现在也找不到常驻编辑来维护版面数据，及时报告机器人收录视频准确与否的样子（泪）
西瓜视频的索引的话这里安排到日程上了，尽请期待（bushi

**Comment by GDWGH** [comment]
很早的bug？
我拿手机edge看帕秋站（习惯用电脑版网页） 
结果手机版和电脑版数据不相通
![手机edge版本](https://i.loli.net/2021/02/27/UjVKRg8OWnBluML.png)
![手机版显示](https://i.loli.net/2021/02/27/2qdaTiWZNGnpxcM.png)
![电脑版显示](https://i.loli.net/2021/02/27/zihLTgQSbXpeW1H.png)

**Comment by GDWGH** [comment]
再补充 2020/2/27 
在安装Linux里的界面 打开系统的浏览器（Firefox 忘记是什么版本了） 
linux bug回报地址-换帕秋站地址 进帕秋站
结果阴阳玉旋转加载画面和整个网页都不显示

**Comment by GDWGH** [comment]
> 再补充 2020/2/27
> 在安装Linux里的界面 打开系统的浏览器（Firefox 忘记是什么版本了）
> linux bug回报地址-换帕秋站地址 进帕秋站
> 结果阴阳玉旋转加载画面和整个网页都不显示

ubuntu

**Comment by wrzrmzx** [comment]
数据不相通的原因是因为当时考虑的是第二轮子页面同时兼容电脑端和移动端有亿点困难，所以就把移动端项目和手机端项目分开来做了来着（类似bilibili.com和m.bilibili.com）后来发现同时维护两个项目还是有些吃力，所以移动端就基本停滞了
![image.png](https://i.loli.net/2021/02/28/lmwCdzHk4yQgtXN.png)
不过新页面还在努力的完成全响应式的目标（
关于Ubuntu的问题咱这里只能测试基于debian10.7的deepin20系统，没有复现上述的问题，请问能不能F12打开控制台截图一下log呢？

**Comment by GDWGH** [comment]
> 数据不相通的原因是因为当时考虑的是第二轮子页面同时兼容电脑端和移动端有亿点困难，所以就把移动端项目和手机端项目分开来做了来着（类似bilibili.com和m.bilibili.com）后来发现同时维护两个项目还是有些吃力，所以移动端就基本停滞了
> ![image.png](https://camo.githubusercontent.com/d12b398f112ec73a2616abf5431514f1f54fe931c80900b899f1b3047794139b/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30322f32382f6c6d7743647a486b3479516774584e2e706e67)
> 不过新页面还在努力的完成全响应式的目标（
> 关于Ubuntu的问题咱这里只能测试基于debian10.7的deepin20系统，没有复现上述的问题，请问能不能F12打开控制台截图一下log呢？

是在安装系统的时候打开live系统的浏览器 无法保存log
不过可以试试 xubnutu（我安装的就是这个 可以在清华源下载） 安装过程到了 正在复制档案的时候 有一个小页 可以去其他页面 向右到最后一个 然后你会见到可以点开的链接 点进去 然后输入 thvideo.tv

**Comment by GDWGH** [comment]
我现在目前自己用的是edge（Version 76.0.160.015.0.865.076.0.160.0 (官方組建Developer Build官方組建) (64 位元)）（site app模式）+手机的yandex浏览器（chromium） edge（44）（好像是webview什么的 还是chromium）
每个浏览器都使用电脑模式浏览 帕奇站 不过在手机 好像是假电脑模式 不知道在手机版设置一个可以切换ui什么的

**Comment by GDWGH** [comment]
这个好像是以后版本的展望什么的吧。。。（如果有site app的话）
使用cloudflare worker的代理（想法： 打开worker 显示token什么的 然后把token和worker地址填进app里 来访问yt什么的）
具体https://github.com/EtherDream/jsproxy/tree/master/cf-worker

**Comment by wrzrmzx** [comment]
因为帕琪站的桌面版和移动版现在是两个单独的项目，所以切换UI不是很容易搞倒是。。。
如果使用一些方法可以绕过gfw直接让大陆用户不用科学上网看ytb的话。。。可能帕琪站第二天就被请喝茶了（

**Comment by GDWGH** [comment]
好像在我的ubuntu 20（arm64）调试不了源码（卡在安装依赖那里）
[npm-debug.log](https://github.com/PatchyVideo/patchyvideo-vue/files/6177074/npm-debug.log)
[log.log](https://github.com/PatchyVideo/patchyvideo-vue/files/6177075/log.log)

**Comment by zyddnys** [comment]
node版本更新下，至少14

**Comment by GDWGH** [comment]
> node版本更新下，至少14
还是好像不行 好像是因为GitHub同步在我这里很慢？（广东移动） 
显示缺少**-**.json 好像是语言文件

**Comment by zyddnys** [comment]
$ git clone https://github.com/PatchyVideo/patchyvideo-vue.git
$ cd patchyvideo-vue
$ git submodule init
$ git submodule update
要把submodule都给拉下来，语言包在submodule里

**Comment by GDWGH** [comment]
> $ git clone https://github.com/PatchyVideo/patchyvideo-vue.git
> $ cd patchyvideo-vue
> $ git submodule init
> $ git submodule update
> 要把submodule都给拉下来，语言包在submodule里

github源太慢了 我有时候拉取到一半就终止了

**Comment by zyddnys** [comment]
挂个梯子

**Comment by wrzrmzx** [comment]
关于npm i
1.给npm设置代理：npm config set proxy=http://127.0.0.1:8087（端口根据代理软件开放的端口来）
2.使用nrm工具切换镜像（看了一下你用的好像是华为镜像，试一试淘宝镜像）
3.Linux系统的话试一试chmod 777，然后全程不要使用sudo（除非是需要-g的npm包）
4.**不！要！使！用！c！n！p！m！**

**Comment by GDWGH** [comment]
前端弄好了 开始编译后端（arm64还是不给力 最后还是用了intel的mac才成功）
好像对群里的莉莉黑感兴趣 不知道会不会开源呢？

**Comment by wrzrmzx** [comment]
莉莉黑的话因为作者（玲子）说是还没把代码完善所以还暂时没有开源。。。不过有一个基础版的机器人仓库可以拿来先参考一下 https://github.com/shirokurakana/kosuzu
（她本人也在群里）
api的话还在整理后端的接口文档（等到前端告一段落之后），然后新页面使用的是gql可以期待一下
统计系统的话可以问下 @zyddnys 是否可以尝试制作，不过B站官号每周都会有做周报 https://space.bilibili.com/515657675/dynamic

**Comment by zyddnys** [comment]
API之后都将基于gql，可以期待下

**Comment by GDWGH** [comment]
好像帕奇站的logo不同步。。。
上图
![在mac上](https://user-images.githubusercontent.com/57795156/113494660-ee072280-951c-11eb-9d38-d3627794dc4c.png)
![安卓](https://user-images.githubusercontent.com/57795156/113494665-ffe8c580-951c-11eb-8483-e59ab7ba40ac.png)
![Windows 100%下](https://user-images.githubusercontent.com/57795156/113494672-14c55900-951d-11eb-9f4d-6d9abe05a01a.png)
![Windows 75%下](https://user-images.githubusercontent.com/57795156/113494677-2575cf00-951d-11eb-921d-827625aae9b0.png)

**Comment by GDWGH** [comment]
> 好像帕奇站的logo不同步。。。
> 上图
> ![在mac上](https://user-images.githubusercontent.com/57795156/113494660-ee072280-951c-11eb-9d38-d3627794dc4c.png)
> 上面的是在mac上的显示效果
> ![安卓](https://user-images.githubusercontent.com/57795156/113494665-ffe8c580-951c-11eb-8483-e59ab7ba40ac.png)
> 上面的是安卓显示效果
> ![Windows 100%下](https://user-images.githubusercontent.com/57795156/113494672-14c55900-951d-11eb-9f4d-6d9abe05a01a.png)
> ![Windows 75%下](https://user-images.githubusercontent.com/57795156/113494677-2575cf00-951d-11eb-921d-827625aae9b0.png)
> 两个都是Windows下显示效果 第一个是100%下的效果 第二个是75%

个人感觉mac版的好点

**Comment by GDWGH** [comment]
如果后期修改成 logo（指整个logo包括文字）放在服务器上的时候 可以使用下mac字体之类的
mac字体在[这里](https://github.com/GDWGH/files/tree/master/%E6%96%B0%E5%A2%9E%E8%B3%87%E6%96%99%E5%A4%BE)

**Comment by GDWGH** [comment]
好像上传视频太慢了（每次看视频 一个上传视频页面 一个视频）。。。 不知道有没有人做了油猴脚本什么的

**Comment by GDWGH** [comment]
上传视频不支持
https://www.youtube.com/tv#/watch?v=视频id
这是youtube的电视版格式

**Comment by GDWGH** [comment]
> 关于npm i
> 1.给npm设置代理：npm config set proxy=[http://127.0.0.1:8087（端口根据代理软件开放的端口来）](http://127.0.0.1:8087%EF%BC%88%E7%AB%AF%E5%8F%A3%E6%A0%B9%E6%8D%AE%E4%BB%A3%E7%90%86%E8%BD%AF%E4%BB%B6%E5%BC%80%E6%94%BE%E7%9A%84%E7%AB%AF%E5%8F%A3%E6%9D%A5%EF%BC%89)
> 2.使用nrm工具切换镜像（看了一下你用的好像是华为镜像，试一试淘宝镜像）
> 3.Linux系统的话试一试chmod 777，然后全程不要使用sudo（除非是需要-g的npm包）
> 4.**不！要！使！用！c！n！p！m！**

Linux宿主挂了代理 内部还要不要？
那个Linux运行在另外一个Linux里 宿主挂了代理

**Comment by wrzrmzx** [comment]
关于logo：其实现在的logo就是纯文本，字体会根据浏览器的字体进行更换，所以不同机器上运行的效果会有所不同。新版页面的logo已经换成了svg所以就没这个问题了
油管脚本这个继续咨询 @zyddnys ，然后如果能把链接整理好的话帕琪站有一个批量上传的选项
电视版URL格式的正则匹配在做了再做了（
虚拟机的话肯定得继续配，其他的就不太清楚了。。。

**Comment by zyddnys** [comment]
电视的URL匹配做好了

**Comment by GDWGH** [comment]
IE系bug？ 我用几个ie打开历史与贡献都出现了标签莫名变长的bug（应该不用修了 毕竟都没人用了） 
IE:
![IE11](https://user-images.githubusercontent.com/57795156/115131766-16b70e00-a02d-11eb-974c-334115d52db1.png)

![Edge 无bug 用来对比](https://user-images.githubusercontent.com/57795156/115131777-3bab8100-a02d-11eb-80d7-762d4b245686.png)
Edge 无bug 用来对比
![未知版本的360套皮IE浏览器 应该是7？](https://user-images.githubusercontent.com/57795156/115131892-26832200-a02e-11eb-94b3-7d77b3aa58bd.png)
未知版本的360套皮IE浏览器 应该是7？
顺便上传一下这个浏览器
[360安全浏览器单文件.zip](https://github.com/PatchyVideo/patchyvideo-vue/files/6330373/360.zip)

**Comment by wrzrmzx** [comment]
IE那个兼容性早就已经放弃治疗了（（（

**Comment by GDWGH** [comment]
现有新版 close issues（除非还找到一些问题）

**Comment by GDWGH** [comment]
ytb tv太多链接了
https://www.youtube.com/tv/watch#/watch?v=视频id
没适配的链接
![Uploading QQ截图20210521212242.png…]()
